events {}

http {
    server {
        listen 80;

        # React dev server
        location / {
            proxy_pass http://react-app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Spring Boot API
        location /api/ {
            proxy_pass http://springboot-app:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
